//
//  ListUsersViewController.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 9/28/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol ListUsersViewControllerInput {
    func display(users usrs : [ListUsersScene.User])
}

protocol ListUsersViewControllerOutput {
    
    func getUsers() 
}

class ListUsersViewController: UITableViewController, ListUsersViewControllerInput {
    
    
    
    
    var output: ListUsersViewControllerOutput?
    var router: ListUsersRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ListUsersConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        output?.getUsers()
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
    
    func display(users usrs: [ListUsersScene.User]) {
        
    }

}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension ListUsersViewController: ListUsersPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
