//
//  ListUsersPresenter.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 9/28/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ListUsersPresenterInput {
    
}

protocol ListUsersPresenterOutput: class {
    
}

class ListUsersPresenter: ListUsersPresenterInput {
    
    weak var output: ListUsersPresenterOutput?
    
    // MARK: Presentation logic
    
}
