//
//  ListUsersModels.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 9/28/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct ListUsersScene {
    
    struct User  {
        var name : String
        var phoneNumber : String 
    }
}
