//
//  GetFriendsAPIWorker.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates


class GetFriendsAPIWorker {
    // MARK: Business Logic
    
    func doSomeWork() {
        // NOTE: Do the work
    }
    init(withRequest )
}
