//
//  ListFrendsInteractor.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ListFrendsInteractorInput {
    
}

protocol ListFrendsInteractorOutput {
    
}

protocol ListFrendsDataSource {
    
}

protocol ListFrendsDataDestination {
    
}

class ListFrendsInteractor: ListFrendsInteractorInput, ListFrendsDataSource, ListFrendsDataDestination {
    
    var output: ListFrendsInteractorOutput?
    
    
    // MARK: Business logic
    

}
