//
//  ListFrendsRouter.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol ListFrendsRouterInput {
    
}

protocol ListFrendsRouterDataSource: class {
    
}

protocol ListFrendsRouterDataDestination: class {
    
}

class ListFrendsRouter: ListFrendsRouterInput {
    
    weak var viewController: ListFrendsViewController!
    weak private var dataSource: ListFrendsRouterDataSource!
    weak var dataDestination: ListFrendsRouterDataDestination!
    
    init(viewController: ListFrendsViewController, dataSource: ListFrendsRouterDataSource, dataDestination: ListFrendsRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
