//
//  ListFrendsViewController.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit
import Domain

protocol ListFrendsViewControllerInput {
    
}

protocol ListFrendsViewControllerOutput {
    func getFriends(withRequest request : ListFrendsScene.ListFriendsRequest)
}

class ListFrendsViewController: UIViewController, ListFrendsViewControllerInput , UITableViewDelegate , UITableViewDataSource{
    
    var output: ListFrendsViewControllerOutput?
    
    var router: ListFrendsRouter?
   
    var users : [Domain.User] = [Domain.User]()
    
    @IBOutlet weak var tableView : UITableView! {
        didSet {
            tableView.delegate = self
            tableView.dataSource = self
        }
    }
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ListFrendsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Requests
    func getListOfFriends(){
        let getFriendsRequest = ListFrendsScene.ListFriendsRequest(myUserId: "1")
        output?.getFriends(withRequest: getFriendsRequest)
    }
    
    // MARK: Display logic
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return users.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return UITableViewCell()
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension ListFrendsViewController: ListFrendsPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
