//
//  ListFrendsPresenter.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ListFrendsPresenterInput {
    
}

protocol ListFrendsPresenterOutput: class {
    
}

class ListFrendsPresenter: ListFrendsPresenterInput {
    
    weak var output: ListFrendsPresenterOutput?
    
    // MARK: Presentation logic
    
}
