//
//  ListFrendsConfigurator.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ListFrendsInteractor: ListFrendsViewControllerOutput, ListFrendsRouterDataSource, ListFrendsRouterDataDestination {
    
    func getFriends(withRequest request: ListFrendsScene.ListFriendsRequest) {
        
    }
}


extension ListFrendsPresenter: ListFrendsInteractorOutput {
}

class ListFrendsConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = ListFrendsConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: ListFrendsViewController) {
        
        let presenter = ListFrendsPresenter()
        presenter.output = viewController
        
        let interactor = ListFrendsInteractor()
        interactor.output = presenter
        
        let router = ListFrendsRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
