//
//  AddUsersConfigurator.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension AddUsersInteractor: AddUsersViewControllerOutput, AddUsersRouterDataSource, AddUsersRouterDataDestination {
}

extension AddUsersPresenter: AddUsersInteractorOutput {
}

class AddUsersConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = AddUsersConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: AddUsersViewController) {
        
        let presenter = AddUsersPresenter()
        presenter.output = viewController
        
        let interactor = AddUsersInteractor()
        interactor.output = presenter
        
        let router = AddUsersRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
