//
//  AddUsersPresenter.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol AddUsersPresenterInput {
    
}

protocol AddUsersPresenterOutput: class {
    
}

class AddUsersPresenter: AddUsersPresenterInput {
    
    weak var output: AddUsersPresenterOutput?
    
    // MARK: Presentation logic
    
}
