//
//  AddUsersRouter.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol AddUsersRouterInput {
    
}

protocol AddUsersRouterDataSource: class {
    
}

protocol AddUsersRouterDataDestination: class {
    
}

class AddUsersRouter: AddUsersRouterInput {
    
    weak var viewController: AddUsersViewController!
    weak private var dataSource: AddUsersRouterDataSource!
    weak var dataDestination: AddUsersRouterDataDestination!
    
    init(viewController: AddUsersViewController, dataSource: AddUsersRouterDataSource, dataDestination: AddUsersRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
