//
//  AddUsersInteractor.swift
//  SwiftCleanArchitecture
//
//  Created by Wassim on 10/16/17.
//  Copyright (c) 2017 wassimseif. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol AddUsersInteractorInput {
    
}

protocol AddUsersInteractorOutput {
    
}

protocol AddUsersDataSource {
    
}

protocol AddUsersDataDestination {
    
}

class AddUsersInteractor: AddUsersInteractorInput, AddUsersDataSource, AddUsersDataDestination {
    
    var output: AddUsersInteractorOutput?
    
    // MARK: Business logic
    

}
